CARDS_LAYOUT = (8, 4)
CARD_SIZE = (80, 100)
CARD_REVERSE_COLOR = "green"
COLLECTED_CARD_COLOR = "red"
VISIBLE_CARD_COLOR = "white"

FOOTER_HEIGHT = 200
MARGIN = 25

BOARD_WIDTH = CARD_SIZE[0] * CARDS_LAYOUT[0]
BOARD_HEIGHT = CARD_SIZE[1] * CARDS_LAYOUT[1] + FOOTER_HEIGHT

WINDOW_WIDTH = BOARD_WIDTH + 2 * MARGIN
WINDOW_HEIGHT = BOARD_HEIGHT + 2 * MARGIN